on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          components: rustfmt, clippy
          toolchain: stable
          default: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        name: Check Code Format 🔧
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/cargo@v1
        name: Run Clippy Lints 🔨
        with:
          command: clippy
          args: --all-targets

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        name: Running Tests 🚀
        with:
          command: test
          args: --workspace

  test-miri:
    name: Test (miri)
    runs-on: ubuntu-latest
    env:
      TEST_FAST: 1
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          components: miri
          toolchain: nightly
          default: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        name: Running Tests 🚀
        env:
          MIRIFLAGS: -Zmiri-disable-isolation -Zmiri-disable-stacked-borrows # which breaks tokio from time to time
        with:
          command: miri
          args: test
